# Generated by Django 4.2.4 on 2023-08-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='branch',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='starting_year',
            field=models.IntegerField(default=2021),
        ),
    ]
