# Generated by Django 4.2.4 on 2023-08-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_staff_date_of_joined_alter_staff_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='tutor',
        ),
    ]
