# Generated by Django 4.2.4 on 2023-08-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed_course',
            field=models.BooleanField(default=False),
        ),
    ]
