# Generated by Django 4.2.4 on 2023-08-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_class_branch_student_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='branch',
            new_name='dept',
        ),
    ]
