# Generated by Django 4.2.4 on 2023-08-03 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_branch_student_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='tutor',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.staff'),
            preserve_default=False,
        ),
    ]
